### ISSUE TITLE
Mission Crate Didn't Spawn

### ISSUE THREAD

**Issue by MollyXVI** [worldwidesorrow/Wicked-Ai-Overpoch#10]
So some of my players did this a mission where the was only 3 ai and the crate didn't spawn.
Because the crate wasn't there the mission couldn't complete even tho there was 0 Ai remaining.
http://steamcommunity.com/sharedfiles/filedetails/?id=1222317502

**Comment by worldwidesorrow** [comment]
Problems like this tend to occur occasionally. Check the server rpt for errors when this happens. Historically, we have found that errors like this occur when the server fps is really low.
