### ISSUE TITLE
Unarmed AI, Mission Not Completeing and Mission Crate

### ISSUE THREAD

**Issue by MollyXVI** [worldwidesorrow/Wicked-Ai-Overpoch#11]
http://steamcommunity.com/sharedfiles/filedetails/?id=1223068124

So i killed all Ai, Went to the crate and i saw this: http://steamcommunity.com/sharedfiles/filedetails/?id=1223068380
This mission also had an Unarmed Ai
Issues i've had with Unarmed AI: They Have God Mode, When they are Hit, they go in one direction without stop until they disappears, They aren't on Ai Count on Map

And why is there Unarmed AI?

Console: https://paste.md-5.net/keveyebije.tex
spawn_group.sqf: https://paste.md-5.net/hucoyekuqu.coffee

Also, what is debug_mode = false;	// enable debug

**Comment by worldwidesorrow** [comment]
That is what a crate looks like before it is wiped. There is a default crate loadout in certain crate types in Arma. WAI has a script that wipes it when it spawns. Unarmed AI typically occur when there is an incorrect weapon classname. Check your server rpt for errors.
