### ISSUE TITLE
Need Fix ASAP

### ISSUE THREAD

**Issue by MollyXVI** [worldwidesorrow/Wicked-Ai-Overpoch#12]
If one mission Spawns without crate, it cannot be completed for some stupid reason and when this happens, it stops new missions from starting. What the fuck is this shit, there is nothing in the rpt that explains why this is happening. This is just one of many issues.
Another issue si that a missions spawns with 3-4 AI and nothign else, no buildings or vehicles, only the crate and that crate is not emptied, meaning that players on my server can get a shit ton of free shit that their not supose to have, example: 400 Stanag rounds or 50 Grenades and 20 Satchel Charges.

How do i/we prevent all this from happening??
If this cannot be fixed im gonna have to Disable WAI for good.

**Comment by worldwidesorrow** [comment]
No one else has reported these issues. I don't know what is wrong with your server.

**Comment by MollyXVI** [comment]
If i encounter an issue again, can i give u my RPT and you'll have a look at it?

**Comment by kingpapawawa** [comment]
sounds like server fps to me.

**Comment by MollyXVI** [comment]
Server fps is always 25-35 fps and i've set the WAI Config file to not
spawn if lower than 22 fps

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MollyXVI** [comment]
This is the only error im getting in my RPT when either the crate doesnt spawn or the crate doesnt empty:
`23:12:46 Error in expression <n {
for "_i" from 1 to _mags do {
_unit addMagazine _magazine;
};
_unit addweapo>
23:12:46   Error position: <addMagazine _magazine;
};
_unit addweapo>
23:12:46   Error addmagazine: Type Bool, expected Array,String
23:12:46 File z\addons\dayz_server\WAI\compile\spawn_group.sqf, line 141`

**Comment by worldwidesorrow** [comment]
That is caused by a bad weapon classname in one of the arrays.

**Comment by MollyXVI** [comment]
Fixed, one of the classnames was "V", probably a copy-paste fail, sorry for all the frustration and thank you for ur help
